@host = http://localhost:5173

###
### Announcements
###

GET {{host}}/api/announcements
Accept: application/json

###

GET {{host}}/api/announcements/1
Accept: application/json

###

POST {{host}}/api/announcements
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc19hZG1pbiI6dHJ1ZSwiaWF0IjoxNzYzMjc5NzMxLCJleHAiOjE3OTQ4MzczMzEsInN1YiI6IjMifQ.4ZkL0AUTMbkWNLQRBsphuPltw8lgnVoq48rD775ymjw

{
  "sort_datetime": "2025-10-17T12:27:00Z",
  "config": ""
}

###

PUT {{host}}/api/announcements/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc19hZG1pbiI6dHJ1ZSwiaWF0IjoxNzYzMjc5NzMxLCJleHAiOjE3OTQ4MzczMzEsInN1YiI6IjMifQ.4ZkL0AUTMbkWNLQRBsphuPltw8lgnVoq48rD775ymjw

{
  "sort_datetime": "2025-10-17T12:27:00Z",
  "config": "updated"
}

###

DELETE {{host}}/api/announcements/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc19hZG1pbiI6dHJ1ZSwiaWF0IjoxNzYzMjc5NzMxLCJleHAiOjE3OTQ4MzczMzEsInN1YiI6IjMifQ.4ZkL0AUTMbkWNLQRBsphuPltw8lgnVoq48rD775ymjw

###
### Bookings
###

GET {{host}}/api/bookings
Accept: application/json

###

GET {{host}}/api/bookings/1
Accept: application/json

###

POST {{host}}/api/bookings
Accept: application/json
Content-Type: application/json

{
  "user_id": null,
  "service_id": null,
  "booking_datetime": "2025-10-20T08:00:00Z",
  "notes": "...created..."
}

###

PUT {{host}}/api/bookings/1
Accept: application/json
Content-Type: application/json

{
  "user_id": null,
  "service_id": null,
  "booking_datetime": "2025-10-20T08:00:00Z",
  "notes": "...updated..."
}

###

DELETE {{host}}/api/bookings/1
Accept: application/json

###
### Services
###

GET {{host}}/api/services
Accept: application/json

###

GET {{host}}/api/services/1
Accept: application/json

###

POST {{host}}/api/services
Accept: application/json
Content-Type: application/json

{
  "config": "service config"
}

###

PUT {{host}}/api/services/1
Accept: application/json
Content-Type: application/json

{
  "config": "updated service config"
}

###

DELETE {{host}}/api/services/1
Accept: application/json

###
### Feedback
###

GET {{host}}/api/feedback
Accept: application/json

###

GET {{host}}/api/feedback/1
Accept: application/json

###

POST {{host}}/api/feedback
Accept: application/json
Content-Type: application/json

{
  "email": "abc@example.com",
  "subject": "new feedback",
  "message": "feedback message"
}

###

POST {{host}}/api/account/register
Content-Type: application/json

{
  "given_names": "John",
  "last_name": "Citizen",
  "email": "john+citizen@example.invalid",
  "phone": "0411111111",
  "password": "hunter2!"
}

###

POST {{host}}/api/account/login
Accept: application/json
Content-Type: application/json

{
  "email": "john+citizen@example.invalid",
  "password": "hunter2!"
}

###

POST {{host}}/api/account/info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc19hZG1pbiI6dHJ1ZSwiaWF0IjoxNzYzMjc5NzMxLCJleHAiOjE3OTQ4MzczMzEsInN1YiI6IjMifQ.4ZkL0AUTMbkWNLQRBsphuPltw8lgnVoq48rD775ymjw
